### ISSUE TITLE
Functional lock screen

### ISSUE THREAD

**Issue by piebaker** [joamjoamjoam/SteamDeckThemes#2]
Would be awesome to grab a remix in the same style of the OG lock theme, but with date/time/battery/charge time. 
Thought i'd throw it in here as it seems you're the only one with a custom lock screen on decky, and it would be awesome to steal that feature over from crankshaft, its so useful

**Comment by joamjoamjoam** [comment]
Not sure what you mean exactly. Can you link a picture?

**Comment by piebaker** [comment]
Sure!
[This link](https://imgur.com/a/9ByujKS) is for the crankshaft loaders improved lock screen. Something along those lines, vanilla lockscreen with 12 or 24hr time, a charging ETA, battery level, date, time, possibly different backgrounds

**Comment by joamjoamjoam** [comment]
Ah i see. Css loader only lets you rearrange stuff thats already there. You would need to wrote a plugin to add stuff like batt percentage. 

Custom backgrounds are easily doable you just have to make your own theme to add one.

**Comment by My1** [comment]
> Custom backgrounds are easily doable you just have to make your own theme to add one.

or use V2, which comes out soon.

**Comment by piebaker** [comment]
> > Custom backgrounds are easily doable you just have to make your own theme to add one.
> 
> or use V2, which comes out soon.

V2? Got a link for it by any chance? Git repo,discord server etc?

**Comment by My1** [comment]
#5

**Comment by My1** [comment]
will get pushed to the theme store soon, as the lockscreen update hit stable
